services:
    pgsql:
        restart: no
        image: postgres:latest
        volumes:
            - data:/var/lib/postgresql/data
        ports:
            - 0.0.0.0:5432:5432
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    chromadb:
        restart: no
        image: chromadb/chroma:latest
        volumes:
            - chroma-data:/chroma/chroma
        ports:
        - "8001:8001"
        command: "--workers 1 --host 0.0.0.0 --port 8001 --proxy-headers --timeout-keep-alive 30"


volumes:
    data:
        driver: local
    chroma-data:
        driver: local