services:
    pgsql:
        restart: always
        image: postgres:latest
        volumes:
            - data:/var/lib/postgresql/data
        ports:
            - 0.0.0.0:5432:5432
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
    data:
        driver: local