services:
    pgsql:
        restart: no
        image: postgres:latest
        volumes:
            - data:/var/lib/postgresql/data
        ports:
            - 0.0.0.0:5432:5432
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    chromadb:
        restart: no
        image: chromadb/chroma:latest
        volumes:
            - chroma-data:/chroma/chroma
        ports:
            - "8001:8001"
        environment:
            - CHROMA_HOST_PORT=8001
            - CHROMA_HOST_ADDR=0.0.0.0


volumes:
    data:
        driver: local
    chroma-data:
        driver: local